name: protos
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.2.0

dependencies:
  grpc: ^3.2.4
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
